---
openapi: 3.0.1
info:
  title: MultiWoven API
  version: 1.0.0
paths:
  "/api/v1/models":
    get:
      summary: Lists all models
      tags:
      - Models
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            description:
                              type: string
                            query:
                              type: string
                            query-type:
                              type: string
                            created-at:
                              type: string
                              format: date-time
                            updated-at:
                              type: string
                              format: date-time
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                      first:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                      last:
                        type: string
    post:
      summary: Creates a model
      tags:
      - Models
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Model created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                          query:
                            type: string
                          query-type:
                            type: string
                          created-at:
                            type: string
                            format: date-time
                          updated-at:
                            type: string
                            format: date-time
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                model:
                  type: object
                  properties:
                    connector_id:
                      type: integer
                    name:
                      type: string
                    query:
                      type: string
                    query_type:
                      type: string
                  required:
                  - connector_id
                  - name
                  - query
                  - query_type

  "/api/v1/models/{id}":
    get:
      summary: Retrieves a model
      tags:
      - Models
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                          query:
                            type: string
                          query-type:
                            type: string
                          created-at:
                            type: string
                            format: date-time
                          updated-at:
                            type: string
                            format: date-time
    put:
      summary: Updates a model
      tags:
      - Models
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Model updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
                          description:
                            type: string
                          query:
                            type: string
                          query-type:
                            type: string
                          created-at:
                            type: string
                            format: date-time
                          updated-at:
                            type: string
                            format: date-time
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                model:
                  type: object
                  properties:
                    connector_id:
                      type: integer
                    name:
                      type: string
                    query:
                      type: string
                    query_type:
                      type: string
                  required:
                  - connector_id
                  - name
                  - query
                  - query_type
    delete:
      summary: Deletes a model
      tags:
      - Models
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Model deleted

  # Workspaces
  "/api/v1/workspaces":
    get:
      summary: Lists all workspaces
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Workspaces retrieved
    post:
      summary: Creates a workspace
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Workspace created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workspace:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                  - name
              required:
              - name
  "/api/v1/workspaces/{id}":
    put:
      summary: Updates a workspace
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Workspace updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workspace:
                  type: object
                  properties:
                    name:
                      type: string
    delete:
      summary: Deletes a workspace
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Workspace deleted

  "/api/v1/workspaces/{workspace_id}/workspace_users":
    post:
      summary: Adds a user to a workspace
      tags:
      - WorkspaceUsers
      security:
      - bearerAuth: []
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: User added to workspace
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workspace_user:
                  type: object
                  properties:
                    email:
                      type: string
                    role:
                      type: string
                  required:
                  - email
                  - role
              required:
              - workspace_user
  "/api/v1/workspaces/{workspace_id}/workspace_users/{id}":
    put:
      summary: Updates a user's role in a workspace
      tags:
      - WorkspaceUsers
      security:
      - bearerAuth: []
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: integer
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: User role updated in workspace
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
              required:
              - role
    delete:
      summary: Removes a user from a workspace
      tags:
      - WorkspaceUsers
      security:
      - bearerAuth: []
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: integer
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: User removed from workspace

servers:
- url: https://api.multiwoven.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
